azure_region       = "West Europe"
kubernetes_version = "1.14.8"
esoutce_group      = "AKSCluster-RG"
acr_name           = "aksterraformacrdemo2"
keyvault_rg        = "AKSTerraform-RG"
keyvault_name      = "todorovkv"